---

- hosts: all
  become: true

  vars:
    oc_version: 2.1.0.2
    oc_download_url: https://codeload.github.com/opencart/opencart/zip/{{oc_version}}

  tasks:
  - name: disable selinux
    selinux: policy=targeted state=permissive

  - name: disable selinux on boot
    lineinfile: dest={{item}} regexp=^SELINUX= line=SELINUX=permissive
    with_items:
    - /etc/sysconfig/selinux

  - name: install pkgs
    yum: name={{item}} state=installed
    with_items:
    - php-mysql
    - php-gd
    - php-mcrypt
    - php-cli
    - httpd
    - mod_ssl
    - unzip
    - mariadb-server
    - MySQL-python

  - name: download opencart to /tmp
    get_url: url={{oc_download_url}} dest=/tmp/opencart-{{oc_version}}.zip

  - name: unzip opencart in /tmp
    unarchive: src=/tmp/opencart-{{oc_version}}.zip dest=/tmp copy=no creates=/tmp/opencart-{{oc_version}}

  - name: move opencart to /var/www/html
    command: mv /tmp/opencart-{{oc_version}}/upload/* /var/www/html
    args:
      creates: /var/www/html/admin

  - name: touch config-dest.php
    copy: content="" dest=/var/www/html/{{item}} force=no
    with_items:
    - config.php
    - admin/config.php

  - name: chmod g+w and chown apache:apache
    file: path=/var/www/html/{{item}} owner=apache group=apache mode=0664
    with_items:
    - image
    - image/cache
    - image/catalog
    - system/storage/cache
    - system/storage/logs
    - system/storage/download
    - system/storage/upload
    - system/storage/modification
    - config.php
    - admin/config.php

  - name: start webserver and mysql
    service: name={{item}} state=started enabled=true
    with_items:
    - httpd
    - mariadb

  - name: create opencart db in mysql
    mysql_db: name=opencart state=present

  - name: install opencart
    command: php cli_install.php install --db_hostname localhost --db_username root --db_database opencart --db_driver mysqli --username admin --password admin --email root@localhost --http_server http://localhost:8080/
    args:
      chdir: /var/www/html/install
