---

- hosts: all
  become: true

  vars:
    oc_version: 2.1.0.2
    oc_download_url: https://codeload.github.com/opencart/opencart/zip/{{oc_version}}

  tasks:
  - name: disable selinux
    selinux: policy=targeted state=permissive

  - name: disable selinux on boot
    command: sed -i "s:SELINUX=enforcing:SELINUX=permissive:" /etc/sysconfig/selinux

  - name: install pkgs
    yum: name={{item}} state=installed
    with_items:
    - php-mysql
    - php-gd
    - php-mcrypt
    - httpd
    - mod_ssl
    - unzip
    - mariadb-server

  - name: download opencart to /tmp
    get_url: url={{oc_download_url}} dest=/tmp/opencart-{{oc_version}}.zip

  - name: unzip opencart in /tmp
    unarchive: src=/tmp/opencart-{{oc_version}}.zip dest=/tmp copy=no

  - name: move opencart to /var/www/html
    copy: remote_src=true src=/tmp/opencart-{{oc_version}}/upload/ dest=/var/www/html

  - name: touch config-dest.php
    copy: content="" dest=/var/www/html/{{item}}
    with_items:
    - config.php
    - admin/config.php

  - name: chmod g+w and chown apache:apache
    file: path=/var/www/html/{{item}} owner=apache group=apache mode=0664
    with_items:
    - image
    - image/cache
    - image/catalog
    - system/storage/cache
    - system/storage/logs
    - system/storage/download
    - system/storage/upload
    - system/storage/modification
    - config.php
    - admin/config.php

  - name: start webserver and mysql
    service: name={{item}} state=started enable=true
    with_items:
    - httpd
    - mariadb

  - name: create opencart db in mysql
    mysql_db: name=opencart state=present

