---

- hosts: all
  become: true

  vars:
    oc_images:
    - name: logo.png
    - name: avocado-heart.jpg
      url: http://img2.timeinc.net/health/images/slides/avocado-heart-400x400.jpg
    - name: tomato.jpg
      url: https://timewellness.files.wordpress.com/2012/09/tomato.jpg?w=480&h=320&crop=1

  roles:
  - opencart
